version: "3.8"

services:
  react-dev:
    container_name: react-dev
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
    stdin_open: true
    volumes:
      - "./app:/app"
  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - IP=0.0.0.0
    stdin_open: true
    volumes:
      - "./api:/api"
