version: "3.8"

services:
  react-prod:
    container_name: react-prod
    build:
      context: app
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    stdin_open: true
  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
    stdin_open: true