FROM node:14.8-alpine as build

RUN apk add --update --no-cache bash

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --prod --non-interactive --pure-lockfile

COPY . .

RUN yarn build

FROM nginx:alpine

COPY --from=build /app/public /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
